[package]
name = "esplora-client"
version = "0.0.1"
edition = "2018"
authors = ["Alekos Filini <alekos.filini@gmail.com>"]
license = "MIT"
homepage = "https://github.com/bitcoindevkit/rust-esplora-client"
repository = "https://github.com/bitcoindevkit/rust-esplora-client"
documentation = "https://docs.rs/esplora-client/"
description = "Bitcoin Esplora API client library. Supports plaintext, TLS and Onion servers. Blocking or async"
keywords = ["bitcoin", "esplora"]
readme = "README.md"

[lib]
name = "esplora_client"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bitcoin = { version = "0.28.1", features = ["use-serde"] }
log = "^0.4"
ureq = { version = "~2.2.0", features = ["json"], optional = true }
reqwest = { version = "0.11", optional = true, default-features = false, features = ["json"] }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["blocking", "async", "async-https"]
blocking = ["ureq", "ureq/socks"]
async = ["reqwest", "reqwest/socks"]
async-https = ["reqwest/default-tls"]
