[package]
name = "bp-esplora"
version = "0.11.0"
edition = "2018"
authors = ["Alekos Filini <alekos.filini@gmail.com>", "Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
license = "MIT"
homepage = "https://github.com/BP-WG/bp-esplora-client"
repository = "https://github.com/BP-WG/bp-esplora-client"
documentation = "https://docs.rs/bp-esplora/"
description = "Bitcoin Esplora API client library not using rust-bitcoin. Blocking or async"
keywords = ["bitcoin", "esplora"]
readme = "README.md"

[lib]
name = "esplora"
path = "src/lib.rs"

[dependencies]
amplify = { version = "4.0.0", features = ["serde"] }
bp-std = { version = "0.11.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.1.0", features = ["hex"] }
log = "^0.4"
ureq = { version = "2.5.0", features = ["json"], optional = true }
reqwest = { version = "0.11", optional = true, default-features = false, features = ["json"] }

[features]
default = ["blocking", "async", "async-https"]
blocking = ["ureq", "ureq/socks-proxy"]
async = ["reqwest", "reqwest/socks"]
async-https = ["async", "reqwest/default-tls"]
async-https-native = ["async", "reqwest/native-tls"]
async-https-rustls = ["async", "reqwest/rustls-tls"]
async-https-rustls-manual-roots = ["async", "reqwest/rustls-tls-manual-roots"]

[patch.crates-io]
bp-primitives = { git = "https://github.com/BP-WG/bp-core", branch = "primitives" }
bp-std = { git = "https://github.com/BP-WG/bp-std", branch = "psbt" }
